### PR TITLE
User Model-Joseph

### PR DESCRIPTION
**Pull request by JosephThuku**
I created the account and blog post models. though i used the existing user inbiult django model

### CODE REVIEW

**Review by Eugene-Kwaka — COMMENTED** [review]
If you are using the django inbuild user model, you need to extend it using the AbstractUser class so that we can add:
* phone_number
* verification_code 
attributes which are not part of the default django user model attributes. @hellen-22 described how to go about it in one of the github discussions.

**Comment by hellen-22** [comment]
It's best practice to start each word with a capital letter when writing python classes..ie class Account, class Blog

**Comment by hellen-22** [comment]
Also when creating django models you do not need to include id field because it is automatically given by django and its autoincremented. Not unless you want to use a different approach to save the user id eg using UUID as your unique identifier.

My thought

**Review by teslima0 — CHANGES_REQUESTED** [review]
you have done a good job, however i have 2 quick observation in account model.
1. In my opinion, declaring Id field is not necessary since django will do that for you automatically.
2.  secondly,  the unique in name field should not be set to true since we might have multiple user bearing  the same name. instead use username as unique field to differentiate users.
3.  similarly on blogpost model id field should not be declared for same reason sited above

**Pull request closed without merging**
