### PR TITLE
Unit tests of Account and User models

### PR DESCRIPTION
**Pull request by Fredrick-Waihenya**

### CODE REVIEW

**Review by JimmyTron — COMMENTED** [review]
Simply precise.

**Review by sangkips — CHANGES_REQUESTED** [review]
Please normalize adding comments. For example why use assertEqual, hard coding passwords and email. I am very sure someone is asking also about this.

**Comment by sangkips** [comment]
> Please normalize adding comments. For example why use assertEqual, hard coding passwords and email. I am very sure someone is asking also about this.

Tests passes succesfully
Tests

**Comment by Fredrick-Waihenya** [comment]
> Please normalize adding comments. For example why use assertEqual, hard coding passwords and email. I am very sure someone is asking also about this.

I'll comment next time, asssertEqual()  just verifies if the strings returned by the model class user and account are equal to what you have given to the database using __.save()

**Review by JimmyTron — APPROVED** [review]

**Review by sangkips — APPROVED** [review]
All good

**Comment by JimmyTron** [comment]
What if we had all our tests in one place insteadvof having them on idividual apps? 
 What would be the merits of demerits of doing so?

**Pull request merged**
