### PR TITLE
add test folder in the Project i.e CMS folder and delete test.py files in the apps

### PR DESCRIPTION
**Pull request by Eva-Wamuyu**

### CODE REVIEW

**Comment by hellen-22** [comment]
Inside the tests folder, in the accounts folder, rename the file for testing models from tests_models.py to test_models.py. For a minute i could not find the tests using pytest but when i renamed the file to test_models.py the tests were found.

**Comment by Eva-Wamuyu** [comment]
Noted

**Comment by JimmyTron** [comment]
@Eva-Wamuyu there's a conventional way of setting the test module check from the docs.


https://docs.djangoproject.com/en/4.1/topics/testing/

**Comment by Eva-Wamuyu** [comment]
Okay, on it. Thank you.

**Pull request merged**
